name: Daily XML update (8:30 BD time)

on:
  schedule:
    # 02:30 UTC daily = 08:30 Bangladesh time (UTC+6)
    - cron: '30 23 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-feeds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser python-dateutil

      - name: Run fetch_and_publish.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python fetch_and_publish.py

      - name: Commit and push changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Only commit if repo has changes
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Auto-update daily XML feeds (generated) [ci skip]"
            git push
          else
            echo "No changes to commit."
          fi
